[Service]
Host = "edgex-device-snmp-patlite"
Port = 49992
ConnectRetries = 3
Labels = []
OpenMsg = "device snmp patlite in Go started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16


[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = true
File = "/edgex/logs/device-simple.log"
Level = "INFO"

# Pre-define Schedule Configuration
[[Schedules]]
Name = "10sec-schedule"
Frequency = "PT10S"

[[ScheduleEvents]]
Name = "readLights"
Schedule = "10sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/patlite01/AllLights"

# Pre-define Devices
[[DeviceList]]
  Name = "patlite01"
  Profile = "patlite"
  [DeviceList.Addressable]
# change the IP address for your patlite here
    Address = "192.168.0.14"
    Port = 161
    Protocol = "TCP"
